version: '3'

services:
  gptweb:
    container_name: chatgpt-web-midjourney-proxy
    image: ydlhero/chatgpt-web-midjourney-proxy # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 6050:3002
    environment:
      # 必选
      OPENAI_API_KEY:
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_BASE_URL:
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      OPENAI_API_MODEL:
      # 访问权限密钥，可选
      AUTH_SECRET_KEY:
      # midjourney 服务器地址，可选
      MJ_SERVER:
      # midjourney API密钥，可选
      MJ_API_SECRET:
      #API_UPLOADER 是否可以上传 1 可以其他都不可以，可选
      API_UPLOADER:
      #HIDE_SERVER 隐藏服务端 1，可选
      HIDE_SERVER:
      #自定义模型  CUSTOM_MODELS=-gpt-3.5-turbo-0301,gpt-4.5 不显示 gpt-3.5-turbo-0301 新增加 gpt-4.5，可选
      CUSTOM_MODELS:
      #TJ_BAIDU_ID 百度统计ID，可选
      TJ_BAIDU_ID:
      #TJ_GOOGLE_ID 谷歌统计ID，可选
      TJ_GOOGLE_ID:
      #SYS_NOTIFY 系统通知 支持HTML ，可选
      SYS_NOTIFY:
      #FILE_SERVER 文件服务器，可选
      FILE_SERVER:
      #DISABLE_GPT4=1 前端限制GPT4调用，可选
      DISABLE_GPT4:
      # cloudflare r2 存储 10 GB/月 免费 https://www.cloudflare.com/zh-cn/developer-platform/r2/
      R2_DOMAIN:
      R2_BUCKET_NAME:
      R2_ACCOUNT_ID:
      R2_KEY_ID:
      R2_KEY_SECRET:

